# This playbook will take all the necessary steps to create working Wordpress environment on your local Debian machine. 

# ··············································································
# ### Defining host and config variables and completing some pre-tasks.
# ··············································································

---
- hosts: wordpress_server
  become: True
  gather_facts: False

#  vars_files:
#    - './CONFIG.cfg'

  pre_tasks:
    - name: 'Installing python2...'
      apt: 
              pkg : python-simplejson
              state : latest
# ··············································································
# ### TASK
# ··············································································

  tasks               :

# ··············································································
# ### Update
# ··············································································

    - name           : Update
      shell: apt-get update
#      apt            :
#              update_cache : yes

